
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4

/run/initialize

/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 1

#/gps/particle gamma
#/gps/energy 10 MeV
#/gps/pos/type Point
#/gps/pos/centre 0 0 2.5 m
#/gps/ang/type direction
#/gps/ang/direction 0 0 -1
/run/beamOn 50

# proton 210 MeV to the direction (0.,0.,1.)
#/gun/particle proton
#/gun/energy 210 MeV
#/tracking/verbose 2
#/run/beamOn 1
